### PR TITLE
Tasks filters

### PR DESCRIPTION
**Pull request by douglascrp**
Hello @aviriel 

This is a first version of the code that is already working for the issue #5 .
There is just one minor problem though, when the user clicks on a filter, the URL is changed, but the datatables are not reloaded with the data containing the result set for the filtered query.
The only way the user is able to see the change is by reloading the page after clicking on the filter.

Because of that issue I need to ask you NOT to merge it into the master branch, but simply test it as it is and let me know what you think.
Also, if you have an idea on how to fix the reload data, let me know.

I am working on this trying to get ti working ok, but you know, help is always welcome.

I hope to hear something about this from you.

Best regards.

### CODE REVIEW

**Comment by douglascrp** [comment]
I am still trying to figure out what the problem is and what I found so far is only the first generated Alfresco.util.DataTable is reloaded when the filter got changed.

The tests I am doing are related with trying to bind the filterChanged event with all the data tables.

**Comment by aviriel** [comment]
Installed this branch. No idea why only first datatable is reloaded. Scopes maybe?

**Comment by douglascrp** [comment]
@DarkStar1 is trying to find a solution for this.
I have tried so many different things that I am out of ideas right now.

**Comment by douglascrp** [comment]
@aviriel Done, it is working now.
You can test it again and then merge it into the master branch if it is ok.

Thank you @DarkStar1 for the fix.

**Comment by aviriel** [comment]
Nice job, thanks a lot! :)

**Pull request merged**
